# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
        working-directory: ./server
      - run: yarn test
        working-directory: ./server
      - run: yarn deploy
        working-directory: ./server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CAPTCHA_SECRET_KEY: ${{ secrets.CAPTCHA_SECRET_KEY }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CORS_HOST: ${{ secrets.CORS_HOST }}
  ui:
    name: UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
        working-directory: ./ui
      - run: yarn test
        working-directory: ./ui
      - run: yarn build
        working-directory: ./ui
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          REACT_APP_DATA_URL: ${{ secrets.REACT_APP_DATA_URL }}
          REACT_APP_CAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_CAPTCHA_SITE_KEY }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/build